# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.hook.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\EntityService\DateRepeatService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.hook.form.type.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatType
        arguments: [ @service_container ]
    campaignchain.hook.listener.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\EventListener\DateRepeatListener
        arguments: [ @service_container ]