# Copyright 2016 CampaignChain, Inc. <info@campaignchain.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parameters:

services:
    campaignchain.hook.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\EntityService\DateRepeatService
        arguments:
            - "@doctrine"
            - "@campaignchain.core.util.datetime"
            - "@templating"
            - "@campaignchain.core.campaign"
    campaignchain.hook.form.type.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatType
        arguments:
            - '@campaignchain.core.util.datetime'
            - '@campaignchain.hook.campaignchain.date_repeat'
        tags:
            - { name: form.type }
    campaignchain.hook.form.type.campaignchain.date_repeat_daily:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatDailyType
        arguments: [ '@campaignchain.core.util.datetime' ]
        tags:
            - { name: form.type }
    campaignchain.hook.form.type.campaignchain.date_repeat_weekly:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatWeeklyType
        arguments: [ '@campaignchain.core.util.datetime' ]
        tags:
            - { name: form.type }
    campaignchain.hook.form.type.campaignchain.date_repeat_monthly:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatMonthlyType
        arguments: [ '@campaignchain.core.util.datetime' ]
        tags:
            - { name: form.type }
    campaignchain.hook.form.type.campaignchain.date_repeat_yearly:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatYearlyType
        arguments: [ '@campaignchain.core.util.datetime' ]
        tags:
            - { name: form.type }
    campaignchain.hook.form.type.campaignchain.date_repeat_end:
        class: CampaignChain\Hook\DateRepeatBundle\Form\Type\DateRepeatEndType
        arguments: [ '@campaignchain.core.util.datetime' ]
        tags:
            - { name: form.type }
    campaignchain.hook.listener.campaignchain.date_repeat:
        class: CampaignChain\Hook\DateRepeatBundle\EventListener\DateRepeatListener
        arguments: [ '@service_container' ]